version: '3.8'

services:
  postgres:
    image: postgres:14.5
    container_name: sicredi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sicredi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sicredi-net

volumes:
  pgdata:

networks:
  sicredi-net: